export const renderCodeList = (data: string, codeName: string) => {
  console.debug('codeName:', codeName, 'data:', data);
  if (!codeList[codeName]) {
    return '';
  }
  for (let idx = 0; idx < codeList[codeName].length; idx++) {
    if (codeList[codeName][idx].value === data) {
      return codeList[codeName][idx].label;
    }
  }
  return data + ' not in ' + codeName;
};

export const localizeCodeList = (t) => {
  for (const codeListKey in codeList) {
    for (const key in codeList[codeListKey]) {
      const code = codeList[codeListKey][key];
      code.label = t(code.i18nKey);
      console.debug(code.value + '=' + code.label);
    }
  }
};

export const codeList = {
  BizType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '煤盐', i18nKey: 'code_list.BizType.1'},
    {value: '2', label: '化工', i18nKey: 'code_list.BizType.2'},
  ],
  Alignment: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: 'horizontal', label: '水平', i18nKey: 'code_list.Alignment.horizontal'},
    {value: 'vertical', label: '垂直', i18nKey: 'code_list.Alignment.vertical'},
  ],
  YuancangForm: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '圆仓作业表单', label: '圆仓作业表单', i18nKey: 'code_list.YuancangForm.圆仓作业表单'},
  ],
  MonthlyCheckForm: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '月度安全检查', label: '月度安全检查', i18nKey: 'code_list.MonthlyCheckForm.月度安全检查'},
  ],
  SecurityDeclareForm: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '安全声明', label: '安全声明', i18nKey: 'code_list.SecurityDeclareForm.安全声明'},
  ],
  UserBizType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '煤盐', label: '煤盐', i18nKey: 'code_list.UserBizType.煤盐'},
    {value: '化工', label: '化工', i18nKey: 'code_list.UserBizType.化工'},
    {value: '运行', label: '运行', i18nKey: 'code_list.UserBizType.运行'},
  ],
  ShipType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '化工船', i18nKey: 'code_list.ShipType.1'},
    {value: '2', label: '外贸船', i18nKey: 'code_list.ShipType.2'},
    {value: '3', label: '所有船', i18nKey: 'code_list.ShipType.3'},
    {value: '4', label: '液化船', i18nKey: 'code_list.ShipType.4'},
    {value: '5', label: '液化船（乙烯）', i18nKey: 'code_list.ShipType.5'},
    {value: '6', label: '液化船（氯乙烯）', i18nKey: 'code_list.ShipType.6'},
    {value: '7', label: '煤盐船', i18nKey: 'code_list.ShipType.7'},
  ],
  Role: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '角色1', i18nKey: 'code_list.Role.1'},
    {value: '2', label: '角色2', i18nKey: 'code_list.Role.2'},
  ],
  RecipientList: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '港口工作人员', i18nKey: 'code_list.RecipientList.1'},
    {value: '2', label: '船长', i18nKey: 'code_list.RecipientList.2'},
    {value: '3', label: '船员', i18nKey: 'code_list.RecipientList.3'},
    {value: '4', label: '代理商', i18nKey: 'code_list.RecipientList.4'},
    {value: '5', label: '政府人员', i18nKey: 'code_list.RecipientList.5'},
    {value: '6', label: '码头作业人员', i18nKey: 'code_list.RecipientList.6'},
  ],
  PublishStatus: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '未发布', i18nKey: 'code_list.PublishStatus.1'},
    {value: '2', label: '已发布', i18nKey: 'code_list.PublishStatus.2'},
  ],
  FillinStatus: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '未填写', i18nKey: 'code_list.FillinStatus.1'},
    {value: '2', label: '已填写', i18nKey: 'code_list.FillinStatus.2'},
  ],
  SubmissionStatus: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '未报送', i18nKey: 'code_list.SubmissionStatus.1'},
    {value: '2', label: '已报送', i18nKey: 'code_list.SubmissionStatus.2'},
  ],

  OperationMode: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '当面操作终端', i18nKey: 'code_list.OperationMode.1'},
    {value: '2', label: '操作终端(WEB后台)', i18nKey: 'code_list.OperationMode.2'},
    {value: '3', label: '邮件/短信', i18nKey: 'code_list.OperationMode.3'},
  ],
  DisplayPosition: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '小程序', i18nKey: 'code_list.DisplayPosition.1'},
    {value: '2', label: 'WEB后台', i18nKey: 'code_list.DisplayPosition.2'},
  ],
  YesNo: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '是', i18nKey: 'code_list.YesNo.1'},
    {value: '2', label: '否', i18nKey: 'code_list.YesNo.2'},
  ],
  MainSubSectionType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '主区块', i18nKey: 'code_list.MainSubSectionType.1'},
    {value: '2', label: '子区块', i18nKey: 'code_list.MainSubSectionType.2'},
  ],
  SectionType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '标题', i18nKey: 'code_list.SectionType.1'},
    {value: '2', label: '表格', i18nKey: 'code_list.SectionType.2'},
    {value: '3', label: '富文本', i18nKey: 'code_list.SectionType.3'},
    {value: '4', label: '签字盖章', i18nKey: 'code_list.SectionType.4'},
    {value: '5', label: '表头', i18nKey: 'code_list.SectionType.5'},
    {value: '6', label: '表中', i18nKey: 'code_list.SectionType.6'},
    {value: '7', label: '表尾', i18nKey: 'code_list.SectionType.7'},
  ],
  SubSectionType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    // {value: '1', label: '表头', i18nKey: 'code_list.SubSectionType.1'},
    {value: '2', label: '单问题行', i18nKey: 'code_list.SubSectionType.2'},
    // {value: '3', label: '单行告知', i18nKey: 'code_list.SubSectionType.3'},
    // {value: '4', label: '单体表格', i18nKey: 'code_list.SubSectionType.4'},
    // {value: '5', label: '录入用整行', i18nKey: 'code_list.SubSectionType.5'},
    // {value: '6', label: '合计行-不跨列', i18nKey: 'code_list.SubSectionType.6'},
    // {value: '7', label: '合计行-整行合并', i18nKey: 'code_list.SubSectionType.7'},
    // {value: '8', label: '签字盖章', i18nKey: 'code_list.SubSectionType.8'},
    {value: '3', label: '富文本', i18nKey: 'code_list.SubSectionType.3'},
    {value: '9', label: '可添加行', i18nKey: 'code_list.SubSectionType.4'},
  ],
  InputControlType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: 'input', i18nKey: 'code_list.InputControlType.1'},
    {value: '2', label: 'radio', i18nKey: 'code_list.InputControlType.2'},
    {value: '3', label: 'checkbox', i18nKey: 'code_list.InputControlType.3'},
    {value: '4', label: 'textarea', i18nKey: 'code_list.InputControlType.4'},
    {value: '5', label: 'rate', i18nKey: 'code_list.InputControlType.5'},
    {value: '6', label: 'image', i18nKey: 'code_list.InputControlType.6'},
  ],
  DomesticForeignTradeType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '内贸', label: '内贸', i18nKey: 'code_list.DomesticForeignTradeType.1'},
    {value: '外贸', label: '外贸', i18nKey: 'code_list.DomesticForeignTradeType.2'},
  ],
  ContentType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '问题表格', i18nKey: 'code_list.ContentType.1'},
    {value: '2', label: '条款问题', i18nKey: 'code_list.ContentType.2'},
    {value: '3', label: '综合说明', i18nKey: 'code_list.ContentType.3'},
    {value: '4', label: '综合总结', i18nKey: 'code_list.ContentType.4'},
    {value: '5', label: '数据记录', i18nKey: 'code_list.ContentType.5'},
  ],
  SubQuestionType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '序号', i18nKey: 'code_list.SubQuestionType.1'},
    {value: '2', label: '提示文字', i18nKey: 'code_list.SubQuestionType.2'},
    {value: '3', label: '带输入框的富文本', i18nKey: 'code_list.SubQuestionType.3'},
    {value: '4', label: '刷卡签名', i18nKey: 'code_list.SubQuestionType.4'},
    {value: '8', label: '手写签名', i18nKey: 'code_list.SubQuestionType.8'},
    {value: '5', label: '签名时间', i18nKey: 'code_list.SubQuestionType.5'},
    {value: '6', label: '图片上传', i18nKey: 'code_list.SubQuestionType.6'},
    {value: '7', label: '文件上传', i18nKey: 'code_list.SubQuestionType.7'},
  ],
  UserType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '港口工作人员', i18nKey: 'code_list.UserType.1'},
    {value: '2', label: '船长', i18nKey: 'code_list.UserType.2'},
    {value: '4', label: '船员', i18nKey: 'code_list.UserType.4'},
    {value: '5', label: '代理商', i18nKey: 'code_list.UserType.5'},
    {value: '6', label: '政府人员', i18nKey: 'code_list.UserType.6'},
  ],
  UserStatus: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '录入中', i18nKey: 'code_list.UserStatus.1'},
    {value: '2', label: '审核中', i18nKey: 'code_list.UserStatus.2'},
    {value: '3', label: '正常', i18nKey: 'code_list.UserStatus.3'},
    {value: '4', label: '已拉黑', i18nKey: 'code_list.UserStatus.4'},
    {value: '5', label: '已删除', i18nKey: 'code_list.UserStatus.5'},
  ],
  OrgType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '港调', i18nKey: 'code_list.OrgType.1'},
    {value: '2', label: '海事', i18nKey: 'code_list.OrgType.2'},
    {value: '3', label: '海关', i18nKey: 'code_list.OrgType.3'},
    {value: '4', label: '地方政府', i18nKey: 'code_list.OrgType.4'},
  ],
  TurnGroup: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '甲班', label: '甲', i18nKey: 'code_list.TurnGroup.甲'},
    {value: '乙班', label: '乙', i18nKey: 'code_list.TurnGroup.乙'},
    {value: '丙班', label: '丙', i18nKey: 'code_list.TurnGroup.丙'},
    {value: '丁班', label: '丁', i18nKey: 'code_list.TurnGroup.丁'},
    {value: '支持', label: '支持', i18nKey: 'code_list.TurnGroup.支持'},
  ],
  TurnNo: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '白班', label: '白班', i18nKey: 'code_list.TurnNo.白班'},
    {value: '夜班', label: '夜班', i18nKey: 'code_list.TurnNo.夜班'},
  ],

  ReceiptMethod: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '邮件', i18nKey: 'code_list.ReceiptMethod.1'},
    {value: '2', label: '微信', i18nKey: 'code_list.ReceiptMethod.2'},
    {value: '3', label: '短信', i18nKey: 'code_list.ReceiptMethod.3'},
    {value: '4', label: '系统操作', i18nKey: 'code_list.ReceiptMethod.4'},
  ],
  VarDataType: [
    {value: 'string', label: '短文字', i18nKey: 'code_list.VarDataType.string'},
    {value: 'text', label: '长文字', i18nKey: 'code_list.VarDataType.text'},
    {value: 'integer', label: '整数', i18nKey: 'code_list.VarDataType.integer'},
    {value: 'float', label: '浮点数', i18nKey: 'code_list.VarDataType.float'},
    {value: 'date', label: '日期', i18nKey: 'code_list.VarDataType.date'},
    {value: 'time', label: '时间', i18nKey: 'code_list.VarDataType.time'},
    {value: 'datetime', label: '日期时间', i18nKey: 'code_list.VarDataType.datetime'},
    {value: 'boolean', label: '布尔(是/否)', i18nKey: 'code_list.VarDataType.boolean'},
  ],
    VarRequired: [
      {value: true, label: '必填', i18nKey: 'code_list.VarRequired.true'},
      {value: false, label: '非必填', i18nKey: 'code_list.VarRequired.false'}
    ],
  VarInputType: [
    {value: 'label', label: '文本显示', i18nKey: 'code_list.VarInputType.label'},
    // {value: 'calc', label: '计算值', i18nKey: 'code_list.VarInputType.calc'},
    {value: 'text', label: '文本输入框', i18nKey: 'code_list.VarInputType.text'},
    {value: 'textarea', label: '多行文本输入框', i18nKey: 'code_list.VarInputType.textarea'},
    {value: 'checkbox', label: '复选框', i18nKey: 'code_list.VarInputType.checkbox'},
    {value: 'radio', label: '单选框', i18nKey: 'code_list.VarInputType.radio'},
    {value: 'rate', label: '评分', i18nKey: 'code_list.VarInputType.rate'},
    {value: 'sum_of_rate', label: '评分合计', i18nKey: 'code_list.VarInputType.sum_of_rate'},
    {value: 'date', label: '日期', i18nKey: 'code_list.VarInputType.date'},
    {value: 'time', label: '时间', i18nKey: 'code_list.VarInputType.time'},
    {value: 'image', label: '静态图片', i18nKey: 'code_list.VarInputType.image'},
    {value: 'file', label: '文件上传', i18nKey: 'code_list.VarInputType.file'},
    {value: 'picture', label: '图片上传', i18nKey: 'code_list.VarInputType.picture'},
    {value: 'signature_card', label: '刷卡签名', i18nKey: 'code_list.VarInputType.signature_card'},
    {value: 'signature_hand', label: '手写签名', i18nKey: 'code_list.VarInputType.signature_hand'},
    {
      value: 'signature_card_multi_people',
      label: '多人签名',
      i18nKey: 'code_list.VarInputType.signature_card_multi_people'
    },
    {value: 'system', label: '系统预置变量', i18nKey: 'code_list.VarInputType.system'},
  ],
  CargoName: [
    {value: 'PM', label: 'PM', i18nKey: 'code_list.CargoName.PM'},
    {value: 'PO', label: 'PO', i18nKey: 'code_list.CargoName.PO'},
    {value: '苯', label: '苯', i18nKey: 'code_list.CargoName.苯'},
    {value: '苯胺', label: '苯胺', i18nKey: 'code_list.CargoName.苯胺'},
    {value: '二氯乙烷', label: '二氯乙烷', i18nKey: 'code_list.CargoName.二氯乙烷'},
    {value: '甲醇', label: '甲醇', i18nKey: 'code_list.CargoName.甲醇'},
    {value: '氯乙烯', label: '氯乙烯', i18nKey: 'code_list.CargoName.氯乙烯'},
    {value: 'VCM=氯乙烯', label: 'VCM=氯乙烯', i18nKey: 'code_list.CargoName.VCM=氯乙烯'},
    {value: '盐酸', label: '盐酸', i18nKey: 'code_list.CargoName.盐酸'},
    {value: '液碱', label: '液碱', i18nKey: 'code_list.CargoName.液碱'},
    {value: '乙烯', label: '乙烯', i18nKey: 'code_list.CargoName.乙烯'},
    {value: '其他', label: '其他', i18nKey: 'code_list.CargoName.其他'},
    {value: '煤', label: '煤', i18nKey: 'code_list.CargoName.煤'},
    {value: '盐', label: '盐', i18nKey: 'code_list.CargoName.盐'},
  ],
  OperationType: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '装', label: '装', i18nKey: 'code_list.OperationType.1'},
    {value: '卸', label: '卸', i18nKey: 'code_list.OperationType.2'},
  ],
  OperationStatus: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '未开始', i18nKey: 'code_list.OperationStatus.1'},
    {value: '2', label: '作业中', i18nKey: 'code_list.OperationStatus.2'},
    {value: '3', label: '已完成', i18nKey: 'code_list.OperationStatus.3'},
  ],
  OperateStatus: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '未开始', i18nKey: 'code_list.OperateStatus.1'},
    {value: '2', label: '作业中', i18nKey: 'code_list.OperateStatus.2'},
    {value: '3', label: '已完成', i18nKey: 'code_list.OperateStatus.3'},
  ],
  BizTitle: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '经理', label: '经理', i18nKey: 'code_list.BizTitle.经理'},
    {value: '工程师', label: '工程师', i18nKey: 'code_list.BizTitle.工程师'},
    {value: '指导员', label: '指导员', i18nKey: 'code_list.BizTitle.指导员'},
    {value: '值长', label: '值长', i18nKey: 'code_list.BizTitle.值长'},
    {value: '班长', label: '班长', i18nKey: 'code_list.BizTitle.班长'},
    {value: '', label: '无', i18nKey: 'code_list.BizTitle.无'},
  ],
  BizPosition: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '经理', label: '经理', i18nKey: 'code_list.BizPosition.经理'},
    {value: '工程师', label: '工程师', i18nKey: 'code_list.BizPosition.工程师'},
    {value: '指导员', label: '指导员', i18nKey: 'code_list.BizPosition.指导员'},
    {value: '值长', label: '值长', i18nKey: 'code_list.BizPosition.值长'},
    {value: '班长', label: '班长', i18nKey: 'code_list.BizPosition.班长'},
    {value: '副班长', label: '副班长', i18nKey: 'code_list.BizPosition.副班长'},
    {value: '班员', label: '班员', i18nKey: 'code_list.BizPosition.班员'},
  ],
  MenuCode: [
    {value: 'template', label: '模版管理', i18nKey: 'code_list.MenuCode.template'},
    {value: 'form', label: '电子表单', i18nKey: 'code_list.MenuCode.form'},
    {value: 'system', label: '系统设定', i18nKey: 'code_list.MenuCode.system'},
    {value: 'meiyan', label: '煤盐电子作业表', i18nKey: 'code_list.MenuCode.meiyan'},
    {value: 'huagong', label: '化工电子作业表', i18nKey: 'code_list.MenuCode.huagong'},
  ]
};
